[package]
name = "zero"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

keywords = ["zero"]
description = "zero trait"
license = "MIT"
readme = "README.md"
repository = "https://github.com/nathanfaucett/rs-zero.git"
homepage = "https://github.com/nathanfaucett/rs-zero"
